{
 "title": "PTU Benchmarking",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "TPM - Prompts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tpm_context", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "TPM - Completions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "tpm_gen", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rpm", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Thottled requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "throttled_requests", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Time to first token - 95th",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    { "expr": "ttft_95th", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Time to first token - Avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    { "expr": "ttft_avg", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "End to end latency - 95th",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    { "expr": "e2e_95th", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "End to end latency - Avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    { "expr": "e2e_avg", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Utilization - 95th",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "targets": [
    { "expr": "util_95th", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Utilization - Avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "targets": [
    { "expr": "util_avg", "legendFormat": "{{job}}" }
   ]
  }
 ]
}