scrape_configs:
  - job_name: 'endpoint_1'
    scrape_interval: 1s
    static_configs:
      - targets: ['benchmark_endpoint_1:9100']
      
  - job_name: 'endpoint_2'
    scrape_interval: 1s
    static_configs:
      - targets: ['benchmark_endpoint_2:9100']