name: aihub

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  PROMETHEUS_IMAGE_NAME: prometheus
  GRAFANA_IMAGE_NAME: grafana
  BENCHMARKING_GUI_IMAGE_NAME: benchmarking-gui
  BENCHMARKING_API_IMAGE_NAME: benchmarking-api

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"
          include-prerelease: true

      - name: Setup MinVer
        run: |
          dotnet tool install --global minver-cli --version 4.3.0

      - name: Calculate Version
        run: |
          echo "MINVERVERSIONOVERRIDE=$($HOME/.dotnet/tools/minver -t v. -m 1.0 -p preview)" >> $GITHUB_ENV

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lower case REPO
        run: |
          echo "GITHUB_REPOSITORY_LOWER_CASE=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Extract metadata (tags, labels) for grafana
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.PROMETHEUS_IMAGE_NAME }}

      - name: Build and push Docker prometehus image
        uses: docker/build-push-action@v3
        with:
          context: ./config/prometheus/
          file: ./config/prometheus/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY_LOWER_CASE }}/${{ env.PROMETHEUS_IMAGE_NAME }}:${{ env.MINVERVERSIONOVERRIDE }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: MINVERVERSIONOVERRIDE=${{ env.MINVERVERSIONOVERRIDE }}

      - name: Extract metadata (tags, labels) for grafana
        id: meta-grafana
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.GRAFANA_IMAGE_NAME }}

      - name: Build and push Docker image for grafana
        uses: docker/build-push-action@v3
        with:
          context: ./config/grafana/
          file: ./config/grafana/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY_LOWER_CASE }}/${{ env.GRAFANA_IMAGE_NAME }}:${{ env.MINVERVERSIONOVERRIDE }}
          labels: ${{ steps.meta-grafana.outputs.labels }}

      - name: Extract metadata (tags, labels) for gui Docker
        id: meta-gui
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.BENCHMARKING_GUI_IMAGE_NAME }}

      - name: Build and push Docker image for plugin
        uses: docker/build-push-action@v3
        with:
          context: ./python/streamlit/
          file: ./python/streamlit/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY_LOWER_CASE }}/${{ env.BENCHMARKING_GUI_IMAGE_NAME }}:${{ env.MINVERVERSIONOVERRIDE }}
          labels: ${{ steps.meta-gui.outputs.labels }}

      - name: Extract metadata (tags, labels) for api Docker
        id: meta-api
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.BENCHMARKING_API_IMAGE_NAME }}

      - name: Build and push Docker image for fsi plugin
        uses: docker/build-push-action@v3
        with:
          context: ./azure-openai-benchmark
          file: ./azure-openai-benchmark/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY_LOWER_CASE }}/${{ env.BENCHMARKING_API_IMAGE_NAME }}:${{ env.MINVERVERSIONOVERRIDE }}
          labels: ${{ steps.meta-api.outputs.labels }}
